name: RPMLauncher
description: A Minecraft Launcher by RPMTW Team.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  url_launcher:
  path_provider: ^2.0.1
  split_view: ^2.1.1
  path:
  watcher: ^1.0.0
  file_selector_platform_interface: ^2.0.0
  file_selector_linux:
  file_selector_macos:
  file_selector_windows:
  file_selector:
  io: ^1.0.3
  archive: ^3.1.2
  crypto:
  system_info: ^1.0.1
  oauth2: ^2.0.0
  dart_minecraft:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/Minecraft.png
    - images/Forge.jpg
    - images/Fabric.png
    - images/CurseForge.png
    - images/Modrinth.png
    - lang/en_us.json
    - lang/zh_tw.json
    - lang/zh_hk.json
    - lang/zh_cn.json
  fonts:
    - family: font
      fonts:
        - asset: fonts/NotoSansCJKtc-Bold.otf #Source: https://www.google.com/get/noto/