name: rpmlauncher
description: A better Minecraft Launcher that supports cross-platform and many functionalities for you to explore!

publish_to: "none"

version: 1.0.6

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.0.18
  path_provider: ^2.0.1
  split_view: ^3.1.0
  path: ^1.8.0
  archive: ^3.3.0
  crypto: ^3.0.1
  system_info: ^1.0.1
  oauth2: ^2.0.0
  dart_minecraft:
  dynamic_themes:
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  toml: ^0.12.0
  line_icons: ^2.0.1
  flutter_markdown: ^0.6.10
  dio: ^4.0.1
  no_context_navigation: ^2.1.2
  flag: ^6.0.0
  args: ^2.3.0
  contextmenu: ^3.0.0
  provider: ^6.0.2
  pub_semver: ^2.1.0
  dart_big5: ^0.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  rpmlauncher_plugin:
    path: plugin
  io: ^1.0.3
  watcher: ^1.0.1
  xml: ^5.3.1
  smooth_page_indicator: ^1.0.0+2
  quiver: ^3.0.1+1
  dart_discord_rpc:
    git: https://github.com/RPMTW/dart_discord_rpc.git
  uuid: ^3.0.5
  sentry_flutter: ^6.4.0
  feedback: 2.2.1
  desktop_multi_window: ^0.0.2
  window_manager: ^0.2.1
  file_picker: ^4.5.1
  rpmtw_dart_common_library: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # msix: 2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/NotoSansCJKtc-Regular.otf #Source: https://fonts.google.com/noto
    # - family: mono
    #   fonts:
    #     - asset: assets/fonts/NotoSansMono-Medium.ttf #Source: https://fonts.google.com/noto
# msix_config:
#   display_name: RPMLauncher
#   publisher_display_name: The RPMTW Team
#   publisher: E=rpmtw666@gmail.com, CN=ga.rpmtw.rpmlauncher, OU=The RPMTW Team, O=The RPMTW Team, L=TW, S=TW, C=TW
#   identity_name: ga.rpmtw.rpmlauncher
#   logo_path: ./assets/images/Logo.png
#   start_menu_icon_path: ./assets/images/Logo.png
#   tile_icon_path: ./assets/images/Logo.png
#   icons_background_color: "#000000"
#   architecture: x64
#   capabilities: "internetClient,allowElevation,internetClientServer,sharedUserCertificates"
#   certificate_path: ./windows/MsixInstaller/CERTIFICATE.pfx
#   certificate_password: "rpmtw"
#   languages: "zh-tw, zh-cn, zh-hk, en-us, ja-jp"
