name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
         channel: beta
      - run: sudo apt-get update
      - run: sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=alpha" --dart-define="version=1.0.0"
      - run: |
          cd ${{ github.workspace }}/build/linux/x64/release/bundle
          chmod +x RPMLauncher
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: RPMLauncher-${{ github.run_number }}-linux
          path: ${{ github.workspace }}/build/linux/x64/release/bundle
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: |
          flutter config --enable-windows-desktop
          flutter build windows --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=alpha" --dart-define="version=1.0.0"
          flutter pub run msix:create
      - name: copy windows dlls
        run: |
          copy C:\Windows\System32\msvcp140.dll build\windows\runner\Release\msvcp140.dll
          copy C:\Windows\System32\vcruntime140.dll build\windows\runner\Release\vcruntime140.dll
          copy C:\Windows\System32\vcruntime140_1.dll build\windows\runner\Release\vcruntime140_1.dll
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: RPMLauncher-${{ github.run_number }}-windows
          path: ${{ github.workspace }}/build/windows/runner/Release      
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=alpha" --dart-define="version=1.0.0"
      - run: |
          mkdir ${{ github.workspace }}/rpmlauncher.app
          mkdir ${{ github.workspace }}/rpmlauncher.app/rpmlauncher.app
          cp -R -f ${{ github.workspace }}/build/macos/Build/Products/Release/rpmlauncher.app ${{ github.workspace }}/rpmlauncher.app/rpmlauncher.app
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: RPMLauncher-${{ github.run_number }}-macos
          path: ${{ github.workspace }}/rpmlauncher.app
