name: No Response

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "5 * * * *"

permissions:
  issues: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'RPMTW/RPMLauncher' }}
    steps:
      - uses: lee-dohm/no-response@9bb0a4b5e6a45046f00353d5de7d90fb8bd773bb
        with:
          token: ${{ github.token }}
          closeComment: >
            Without additional information, we do not know how to resolve this issue, so we will close this topic.
            Thank you for your contribution.

            如果沒有額外的資訊，我們不知道如何解決此議題，因此我們將關閉此議題。
            感謝您的貢獻。
          daysUntilClose: 14
          responseRequiredLabel: "Waiting for response | 等待回應"
