name: Pull Request Analyze
on: [pull_request]

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-2.9.0-0.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.9.0-0.1.pre
      - run: flutter pub get
      - name: Analyze Flutter
        uses: zgosalvez/github-actions-analyze-dart@524d7c3e24b8bd8feab6c5513871a6bc87b2d97b
      - name: Generate Coverage
        run: |
          flutter test --coverage
        shell: bash
        continue-on-error: true
      - name: Update to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  Test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest] # macos-latest
        include:
          - runs-on: ubuntu-latest
            cache-path: /opt/hostedtoolcache/flutter
          - runs-on: windows-latest
            cache-path: C:\hostedtoolcache\windows\flutter
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cache-path }}
          key: ${{ runner.os }}-flutter-2.9.0-0.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.9.0-0.1.pre
      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - name: Flutter Test
        run: flutter test
