name: Pull Request Analyze
on: [pull_request]

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-2.13.0-0.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.13.0-0.1.pre
      - run: flutter pub get
      - name: Analyze Flutter
        uses: zgosalvez/github-actions-analyze-dart@524d7c3e24b8bd8feab6c5513871a6bc87b2d97b
      - name: Generate Coverage
        run: |
          flutter test --coverage
        shell: bash
        continue-on-error: true
      - name: Update to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  Test-Build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-11]
        include:
          - runs-on: ubuntu-latest
            output-path: build/linux/x64/release/bundle
          - runs-on: windows-latest
            output-path: build/windows/runner/Release
          - runs-on: macos-11
            output-path: build/macos/Build/Products/Release/rpmlauncher.app
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-2.13.0-0.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.13.0-0.1.pre
      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - name: Flutter Test
        if: ${{ !(runner.os == 'macOS') }} # disable test on macOS
        run: |
          flutter pub get
          flutter test
      - name: Build for Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=debug" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Build for Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=debug" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Build for macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=debug" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-${{ runner.os }}-debug
          path: ${{ matrix.output-path}}
          retention-days: 30
